name: Dan's Flix
title: Dan's Flix | LEE
description: Dan's flix is a template for Jekyll inspired by Netflix.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
  - Dan's Flix
show_hero: true
disqus_username: LEE
