name: Jekflix
title: Jekflix | A blog theme for Jekyll
description: Dan's flix is a template for Jekyll inspired by Netflix.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
disqus_username: disqus_username
show_hero: true
